<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $lithuaniaId = 1; 

        $lithuanianCities = [
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Vilnius', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kaunas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Klaipėda', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Šiauliai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Panevėžys', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Alytus', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Marijampolė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Mažeikiai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Jonava', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Utena', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kėdainiai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Telšiai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Tauragė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Ukmergė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Plungė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kretinga', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Palanga', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Radviliškis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Gargždai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Druskininkai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Visaginas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Šilutė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Jurbarkas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Biržai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Rokiškis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kuršėnai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Elektrėnai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Garliava', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Grigiškės', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Prienai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Joniškis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kelme', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Varėna', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kaišiadorys', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Pasvalys', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kupiškis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Zarasai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Šakiai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Molėtai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Anykščiai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Šalčininkai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Širvintos', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Lentvaris', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Trakai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Neringa', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Vievis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Švenčionys', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Ignalina', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Pabradė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Švenčionėliai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Skuodas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kazlų Rūda', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Naujoji Akmenė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Birštonas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Akmenė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Vilkaviškis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Raseiniai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kalvarija', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Lazdijai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Pakruojis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Šilalė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Rietavas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Ariogala', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Vandžiogala', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Vilkija', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Ežerėlis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Jieznas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Skaudvilė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Ramygala', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Dūkštas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Kavarskas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Pandėlys', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Salantai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Smiltynė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Subačius', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Troškūnai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Užventis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Vabalninkas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Varniai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Veisiejai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Venta', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Vidiškiai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Viečiūnai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Virbalis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Žagarė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Baltoji Vokė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Daugai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Dusetos', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Gelgaudiškis', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Linkuva', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Obeliai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Pagėgiai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Priekulė', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Seda', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Simnas', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Tytuvėnai', 'city_description_lt' => ''],
            ['country_id' => $lithuaniaId, 'city_name_lt' => 'Žiežmariai', 'city_description_lt' => ''],
        ];

        foreach ($lithuanianCities as $city) {
            City::create($city);
        }
    }
}